FROM curlimages/curl:latest as graal

#Purposely been split to use caching
RUN curl -L -o /tmp/graal.tar.gz https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_linux-aarch64_bin.tar.gz

RUN tar -xzf /tmp/graal.tar.gz -C /tmp/

RUN GRAAL=$(ls -d /tmp/graalvm*) && mv $GRAAL /tmp/graalvm

FROM maven:3.8.8-eclipse-temurin-17 as build

RUN apt update && apt-get install -y build-essential libz-dev zlib1g-dev

COPY --from=graal /tmp/graalvm /usr/graalvm/

ENV JAVA_HOME=/usr/graalvm

WORKDIR /usr/src/

COPY . .

RUN --mount=type=cache,target=/root/.m2 mvn -Pnative native:compile

FROM ubuntu

COPY --from=build ["/usr/src/target/test-rest", "/usr/src/src/main/resources/application.properties", "/"]

ENTRYPOINT ["/test-rest"]